# golangci-lint configuration for OSRS Grand Exchange Tracker Backend
# See: https://golangci-lint.run/usage/configuration/

run:
  # Timeout for analysis
  timeout: 5m
  
  # Use all available CPU cores
  concurrency: 4
  
  # Exit code when at least one issue was found
  issues-exit-code: 1
  
  # Include test files
  tests: true
  
  # Go version to target
  go: "1.24.0"

output:
  # Colored output
  formats:
    - format: colored-line-number
  
  # Print lines of code with issue
  print-issued-lines: true
  
  # Print linter name in the end of issue text
  print-linter-name: true
  
  # Sort results by: filepath, line and column
  sort-results: true

linters-settings:
  # Errcheck: checks for unchecked errors
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (*github.com/gofiber/fiber/v2.Ctx).JSON
      - (*go.uber.org/zap.SugaredLogger).Sync
  
  # Govet: examines Go source code and reports suspicious constructs
  govet:
    enable-all: true
    disable:
      - shadow  # Can be too strict for shadowing variables
  
  # Gocyclo: computes cyclomatic complexities
  gocyclo:
    min-complexity: 15
  
  # Gofmt: checks whether code was gofmt-ed
  gofmt:
    simplify: true
  
  # Goimports: checks import statements are formatted according to the 'goimport' command
  goimports:
    local-prefixes: github.com/guavi/osrs-ge-tracker
  
  # Revive: fast, configurable, extensible, flexible linter
  revive:
    ignore-generated-header: true
    severity: warning
    confidence: 0.8
    rules:
      # Naming conventions (aligned with CODING_STANDARDS.md)
      - name: var-naming
        severity: warning
        arguments:
          - ["ID", "URL", "HTTP", "JSON", "API", "DB", "SQL", "SSE", "OSRS", "GE"] # Common initialisms
      
      - name: exported
        severity: warning
      
      - name: package-comments
        severity: warning
      
      # Code quality
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
      
      # Complexity
      - name: cognitive-complexity
        arguments: [20]
      - name: function-result-limit
        arguments: [3]
      - name: argument-limit
        arguments: [5]
      - name: cyclomatic
        arguments: [15]
      - name: max-public-structs
        arguments: [10]
      
      # Naming
      - name: confusing-naming
      - name: confusing-results
  
  # Gocritic: provides diagnostics that check for bugs, performance and style issues
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - whyNoLint  # We'll use nolint comments when needed
      - hugeParam  # Can be too strict
  
  # Misspell: finds commonly misspelled English words in comments
  misspell:
    locale: US
    ignore-words:
      - osrs  # Old School RuneScape
      - ge    # Grand Exchange
  
  # Unparam: reports unused function parameters
  unparam:
    check-exported: false
  
  # Nakedret: finds naked returns in functions greater than a specified length
  nakedret:
    max-func-lines: 30
  
  # Prealloc: finds slice declarations that could potentially be preallocated
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  
  # Unused: checks Go code for unused constants, variables, functions and types
  unused:
    check-exported: false
  
  # Gosec: inspects source code for security problems
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Duplicate of errcheck
      - G304  # File path from variable (too many false positives)
  
  # Dupl: tool for code clone detection
  dupl:
    threshold: 100
  
  # Lll: reports long lines
  lll:
    line-length: 120
    tab-width: 4
  
  # Godot: checks if comments end in a period
  godot:
    scope: declarations
    capital: false
  
  # Gci: controls package import order and makes it deterministic
  gci:
    sections:
      - standard                               # Standard section: captures all standard packages
      - default                                # Default section: contains all imports that could not be matched
      - prefix(github.com/guavi/osrs-ge-tracker) # Custom section: groups all imports with the specified Prefix
    skip-generated: true
    custom-order: true
  
  # Nolintlint: reports ill-formed or insufficient nolint directives
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true

linters:
  # Disable all linters by default
  disable-all: true
  
  # Enable specific linters
  enable:
    # Essential linters (bugs and correctness)
    - errcheck      # Checks for unchecked errors
    - gosimple      # Simplifies code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Go static analysis
    - typecheck     # Type-checks Go code
    - unused        # Checks for unused constants, variables, functions
    
    # Code quality and style
    - revive        # Fast, configurable linter (replaces golint)
    - gofmt         # Checks if code is formatted
    - goimports     # Fixes imports, formats code
    - misspell      # Finds commonly misspelled words
    - unconvert     # Removes unnecessary type conversions
    - unparam       # Reports unused function parameters
    - nakedret      # Finds naked returns
    - prealloc      # Finds slice declarations that could be preallocated
    - gci           # Controls package import order
    - godot         # Checks if comments end in a period
    
    # Complexity
    - gocyclo       # Computes cyclomatic complexities
    - gocognit      # Computes cognitive complexities
    
    # Performance
    - bodyclose     # Checks HTTP response body is closed
    - noctx         # Finds sending http request without context.Context
    
    # Security
    - gosec         # Inspects source code for security problems
    
    # Code duplications
    - dupl          # Code clone detection
    
    # Style
    - lll           # Reports long lines
    - whitespace    # Detects leading/trailing whitespace
    - gocritic      # Provides many diagnostics
    
    # Best practices
    - nolintlint    # Reports ill-formed nolint directives
    - goconst       # Finds repeated strings that could be constants
    - goprintffuncname # Checks that printf-like functions are named correctly
    - errorlint     # Finds misuses of errors

issues:
  # Which dirs to exclude: issues from them won't be reported
  exclude-dirs:
    - bin
    - coverage
    - vendor
    - migrations  # SQL files, not Go
  
  # Make issues output unique by line
  uniq-by-line: true

  # Maximum issues count per one linter
  max-issues-per-linter: 0
  
  # Maximum count of issues with the same text
  max-same-issues: 0
  
  # Show only new issues
  new: false
  
  # Fix found issues (if it's supported by the linter)
  fix: false
  
  # Exclude specific files
  exclude-files:
    - ".*\\.pb\\.go$"  # Skip protobuf generated files
    - ".*_gen\\.go$"   # Skip other generated files
  
  # List of regexps of issue texts to exclude
  exclude:
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
    - "exported (type|method|function) (.+) should have comment or be unexported"
    - "ST1000: at least one file in a package should have a package comment"
  
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
        - lll
    
    # Exclude some linters from running on testutil files
    - path: tests/testutil/
      linters:
        - unused
        - errcheck
    
    # Exclude certain revive rules for main.go
    - path: cmd/api/main\.go
      linters:
        - revive
      text: "deep-exit"
    
    # Allow package-level logger variables (common pattern)
    - linters:
        - revive
      text: "package-level variable"
      path: "internal/(utils|config)/.*\\.go"
    
    # Allow long lines in migrations
    - path: migrations/
      linters:
        - lll
    
    # Ignore error checks for deferred Close() calls
    - linters:
        - errcheck
      source: "defer.*\\.Close\\(\\)"
    
    # Ignore certain gosec warnings
    - linters:
        - gosec
      text: "G404:"  # Use of weak random number generator (math/rand)
    
    # Allow cognitive complexity in handlers (they handle HTTP logic)
    - path: internal/handlers/.*\.go
      linters:
        - gocognit
      text: "cognitive complexity"

severity:
  # Default value is empty string
  default-severity: error
  
  # Rules for mapping linter issues to severity levels
  rules:
    - linters:
        - dupl
      severity: info
    
    - linters:
        - misspell
        - godot
        - lll
      severity: warning
